# Generated by Django 4.2.5 on 2023-09-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deliverypoint',
            table='delivery-point',
        ),
    ]
